---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 08/06/2021 20:39
---

local FrameController, super = MasterCore.Class:Create("FrameController")
MasterCore.FrameController = FrameController

function FrameController:Init(type, name, parent, template, id)
    self = super.Init(self)
    self.frame = CreateFrame(type, name, parent or UIParent, template, id)
    Mixin(self.frame, BackdropTemplateMixin);

    return self
end

function FrameController:InitWithFrame(frame)
    super.Init(self)
    self.frame = frame
    return self
end