---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 18/06/2021 18:38
---
local L = LibStub("AceLocale-3.0"):NewLocale(MASTER_PREPARE_NAME, "enUS")
if not L then return end

L["Food"] = "Food"
L["Drink"] = "Drink"