---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 16/06/2021 10:30
---
local AceConfigDialog = LibStub("AceConfigDialog-3.0")
local AceConfig = LibStub("AceConfig-3.0")
local L = LibStub("AceLocale-3.0"):GetLocale(MASTER_PREPARE_NAME)
local ConfigFoodAndDrink = MasterPrepare.ConfigFoodAndDrink
local FOOD_AND_DRINK_CONFIG_TYPE = MasterPrepare.FOOD_AND_DRINK_CONFIG_TYPE

local Config = {}
MasterPrepare.Config = Config

function Config:Setup()
    self.db = LibStub("AceDB-3.0"):New("MasterPrepareConfig", self:GetDeaults())
    self.food = ConfigFoodAndDrink:Init(FOOD_AND_DRINK_CONFIG_TYPE.FOOD, self.db.char)
    self.drink = ConfigFoodAndDrink:Init(FOOD_AND_DRINK_CONFIG_TYPE.DRINK, self.db.char)

    -- Register config
    AceConfig:RegisterOptionsTable(MASTER_PREPARE_NAME, self:GetOptions())
    AceConfigDialog:AddToBlizOptions(MASTER_PREPARE_NAME)
    AceConfigDialog:AddToBlizOptions(MASTER_PREPARE_NAME, L["Food"], MASTER_PREPARE_NAME, "food")
    AceConfigDialog:AddToBlizOptions(MASTER_PREPARE_NAME, L["Drink"], MASTER_PREPARE_NAME, "drink")
    AceConfigDialog:SetDefaultSize(MASTER_PREPARE_NAME, 400, 500)

    -- Register cmd to open config dialog
    MasterPrepareAddon:RegisterChatCommand(MASTER_PREPARE_CMD, function()
        AceConfigDialog:Open(MASTER_PREPARE_NAME)
    end)
end

function Config:GetOptions()
    return {
        name = MASTER_PREPARE_NAME,
        handler = self,
        type = "group",
        childGroups = "tab",
        args = {
            food = self.food:GetOptions(),
            drink = self.drink:GetOptions(),
        },
    }
end

function Config:GetDeaults()
    return {
       char = {
           food = ConfigFoodAndDrink:GetDefaults(),
           drink = ConfigFoodAndDrink:GetDefaults()
       }
    }
end