---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 18/06/2021 21:22
---
local L = LibStub("AceLocale-3.0"):GetLocale(MASTER_PREPARE_NAME)
local FOOD_AND_DRINK_CONFIG_TYPE = {
    FOOD = "food",
    DRINK = "drink"
}
MasterPrepare.FOOD_AND_DRINK_CONFIG_TYPE = FOOD_AND_DRINK_CONFIG_TYPE

local FoodAndDrinkConfig, super = MasterCore.Class:Create("FoodAndDrinkConfig", MasterCore.Config)
MasterPrepare.FoodAndDrinkConfig = FoodAndDrinkConfig
function FoodAndDrinkConfig:Init(type, db, order)
    self = super.Init(self, db[type])
    self.type = type
    self.order = order

    if self.type == FOOD_AND_DRINK_CONFIG_TYPE.FOOD then
        self.name = L["Food"]
    end

    if self.type == FOOD_AND_DRINK_CONFIG_TYPE.DRINK then
        self.name = L["Drink"]
    end

    return self
end

function FoodAndDrinkConfig:GetOptions()
    local itemName, stat
    if self.type == FOOD_AND_DRINK_CONFIG_TYPE.FOOD then
        itemName = "food"
        stat = "Health Point"
    end

    if self.type == FOOD_AND_DRINK_CONFIG_TYPE.DRINK then
        itemName = "drink"
        stat = "Mana Point"
    end

    return {
        name = self.name,
        type = 'group',
        handler = self,
        order = self.order,
        args = {
            intro = {
                order = self:_AutoIncrementOrder(true),
                type = "description",
                name = "Auto find the most suitable " .. itemName .. " and buy from vendor\n\n",
                width = "full"
            },
            enable = {
                order = self:_AutoIncrementOrder(),
                type = "toggle",
                name = "Enable",
                width = "full",
                set = "Set",
                get = "GetEnable"
            },
            space1 = {
                order = self:_AutoIncrementOrder(),
                type = "description",
                name = "\n\n",
                width = "full"
            },
            minRestock = {
                order = self:_AutoIncrementOrder(),
                type = "range",
                name = "Min Restock Quantity",
                desc = "Restock when it's lower than this value",
                min = 0,
                max = 200,
                step = 1,
                set = "Set",
                get = "GetMinRestock",
                disabled = function()
                    return not self.db.enable
                end
            },
            maxRestock = {
                order = self:_AutoIncrementOrder(),
                type = "range",
                name = "Max Restock Quantity",
                desc = "The maximum number can buy from vendor",
                min = 1,
                max = 200,
                step = 1,
                set = "Set",
                get = "GetMaxRestock",
                disabled = function()
                    return not self.db.enable
                end
            },
            empty = {
                order = self:_AutoIncrementOrder(),
                type = "description",
                name = "",
                width = "full"
            },
            alwaysRestock = {
                order = self:_AutoIncrementOrder(),
                type = "toggle",
                name = "Always restock",
                desc = "Restock even it's not lower than Min Restock Quantity",
                set = "Set",
                get = "GetAlwaysRestock",
                disabled = function()
                    return not self.db.enable
                end
            },
            sellJunks = {
                order = self:_AutoIncrementOrder(),
                type = "toggle",
                name = "Sell junks",
                desc = "Sell all " .. itemName .. "s which has restore value less than the most suitable " .. itemName,
                set = "Set",
                get = "GetSellJunks",
                disabled = function()
                    return not self.db.enable
                end
            },
            actionBarKey = {
                order = self:_AutoIncrementOrder(),
                type = "keybinding",
                name = "Action Bar Key",
                desc = "Set action bar slot to auto swap " .. itemName .. "s in this character's bag to this slot",
                validate = function(_, value)
                    if GetActionSlot(value) == nil then
                        return "This key is not binded to any Action Button yet!"
                    end

                    return true
                end,
                set = "Set",
                get = "GetActionBarKey",
            },
            con = {
                order = self:_AutoIncrementOrder(),
                type = "toggle",
                name = "Prefer conj",
                desc = "Sell all " .. itemName .. "s which has restore value less than the most suitable " .. itemName,
                set = "Set",
                get = "GetSellJunks",
                disabled = function()
                    return not self.db.enable
                end
            },
            header = {
                order = self:_AutoIncrementOrder(),
                type = "header",
                name = "Criteria",
            },
            info = {
                order = self:_AutoIncrementOrder(),
                type = "description",
                name = "The addon will find the most suitable " .. itemName .. " base on these criteria",
                width = "full"
            },
            usable = {
                order = self:_AutoIncrementOrder(),
                type = "toggle",
                name = "Usable",
                desc = "The " .. itemName .. " must be usable by this character",
                set = "SetCriteria",
                get = "GetCriteriaUsable",
                disabled = function()
                    return true
                end
            },
            mostValue = {
                order = self:_AutoIncrementOrder(),
                type = "toggle",
                name = "Most value",
                desc = "The " .. itemName .. " must have restore value closest to this charactor's " .. stat,
                set = "SetCriteria",
                get = "GetCriteriaMostValue",
                disabled = function()
                    return not self.db.enable
                end
            },
            saveBagSpace = {
                order = self:_AutoIncrementOrder(),
                type = "toggle",
                name = "Save bag space",
                desc = "Sell and replace un-full stack " .. itemName .. "s that has the same restore value with the most suitable " .. itemName,
                set = "SetCriteria",
                get = "GetCriteriaSaveBagSpace",
                disabled = function()
                    return not self.db.enable
                end
            },
        }
    }
end

function FoodAndDrinkConfig:GetEnable()
    return self:Get("enable")
end

function FoodAndDrinkConfig:GetMinRestock()
    return self:Get("minRestock")
end

function FoodAndDrinkConfig:GetMaxRestock()
    return self:Get("maxRestock")
end

function FoodAndDrinkConfig:GetAlwaysRestock()
    return self:Get("alwaysRestock")
end

function FoodAndDrinkConfig:GetSellJunks()
    return self:Get("sellJunks")
end

function FoodAndDrinkConfig:GetActionBarKey()
    return self:Get("actionBarKey")
end

function FoodAndDrinkConfig:SetCriteria(info, value)
    local key = self:_GetKey(info)
    self.db.criteria[key] = value
end

function FoodAndDrinkConfig:GetCriteria(info)
    local key = self:_GetKey(info)
    return self.db.criteria[key]
end

function FoodAndDrinkConfig:GetCriteriaUsable()
    return self:GetCriteria("usable")
end

function FoodAndDrinkConfig:GetCriteriaMostValue()
    return self:GetCriteria("mostValue")
end

function FoodAndDrinkConfig:GetCriteriaSaveBagSpace()
    return self:GetCriteria("saveBagSpace")
end

function FoodAndDrinkConfig:GetAllCriteria()
    return self.db.criteria
end

function FoodAndDrinkConfig:GetDefaults()
    return {
        enable = true,
        minRestock = 20,
        maxRestock = 30,
        alwaysRestock = true,
        sellJunks = true,
        criteria = {
            usable = true,
            mostValue = false,
            saveBagSpace = false,
        }
    }
end

