---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 20/06/2021 14:50
---
local GearRepairConfig = MasterPrepare.GearRepairConfig
local GearSellConfig = MasterPrepare.GearSellConfig

local GearConfig, super = MasterCore.Class:Create("GearConfig", MasterCore.Config)
MasterPrepare.GearConfig = GearConfig

function GearConfig:Init(db, order)
    self = super.Init(self, db, order)
    self.name = "Gear"
    self.repair = GearRepairConfig:Init(self.db.repair, 1)
    self.sell = GearSellConfig:Init(self.db.sell, 2)
    return self
end

function GearConfig:GetOptions()
    return {
        name = self.name,
        type = "group",
        childGroups = "tab",
        handler = self,
        order = self.order,
        args = {
            repair = self.repair:GetOptions(),
            sell = self.sell:GetOptions()
        }
    }
end

function GearConfig:GetDefaults()
    return {
        repair = GearRepairConfig:GetDefaults(),
        sell = GearSellConfig:GetDefaults(),
    }
end