---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 20/06/2021 14:50
---
local AutoRepairConfig = MasterPrepare.AutoRepairConfig
local AutoSellConfig = MasterPrepare.AutoSellConfig

local GearConfig, super = MasterCore.Class:Create("GearConfig", MasterCore.Config)
MasterPrepare.GearConfig = GearConfig

function GearConfig:Init(db, order)
    self = super.Init(self, db, order)
    self.name = "Gear"
    self.autoRepair = AutoRepairConfig:Init(self.db.autoRepair, 1)
    self.autoSell = AutoSellConfig:Init(self.db.autoSell, 2)
    return self
end

function GearConfig:GetOptions()
    return {
        name = self.name,
        type = "group",
        childGroups = "tab",
        handler = self,
        order = self.order,
        args = {
            autoRepair = self.autoRepair:GetOptions(),
            autoSell = self.autoSell:GetOptions()
        }
    }
end

function GearConfig:GetDefaults()
    return {
        autoRepair = AutoRepairConfig:GetDefaults(),
        autoSell = AutoSellConfig:GetDefaults(),
    }
end