---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 18/06/2021 21:22
---
local FWActionButtonConfig = MasterPrepare.FWActionButtonConfig
local FW_TYPE = MasterPrepare.FW_TYPE

local PotionConfig, super = MasterCore.Class:Create("PotionConfig", MasterCore.Config)
MasterPrepare.PotionConfig = PotionConfig
function PotionConfig:Init(db, order)
    self = super.Init(self, db, order)
    self.name = "Potion"
    self.healing = {
        actionButton = FWActionButtonConfig:Init(FW_TYPE.HEALING_POTION, self.db.healing.actionButton)
    }
    self.mana = {
        actionButton = FWActionButtonConfig:Init(FW_TYPE.MANA_POTION, self.db.mana.actionButton)
    }
    return self
end

function PotionConfig:GetOptions()

    return {
        name = self.name,
        type = 'group',
        childGroups = "tab",
        handler = self,
        order = self.order,
        args = {
            healing = self.healing.actionButton:GetOptions(),
            mana = self.mana.actionButton:GetOptions(),
        }
    }
end

function PotionConfig:GetDefaults()
    return {
        healing = {
            actionButton = FWActionButtonConfig:GetDefaults(FW_TYPE.HEALING_POTION)
        },
        mana = {
            actionButton = FWActionButtonConfig:GetDefaults(FW_TYPE.MANA_POTION)
        },
    }
end

