---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 18/06/2021 21:22
---
local FWActionButtonConfig = MasterPrepare.FWActionButtonConfig
local FW_TYPE = MasterPrepare.FW_TYPE
local INVENTORY_SLOT_NAME = MasterCore.INVENTORY_SLOT_NAME

local WeaponEnchantConfig, super = MasterCore.Class:Create("WeaponEnchantConfig", MasterCore.Config)
MasterPrepare.WeaponEnchantConfig = WeaponEnchantConfig

function WeaponEnchantConfig:Init(db, order)
    self = super.Init(self, db, order)
    self.name = "Weapon Enchant"
    return self
end

function WeaponEnchantConfig:GetOptions()

    return {
        name = self.name,
        type = 'group',
        handler = self,
        order = self.order,
        args = {
          enable = {
              order = self:_AutoIncrementOrder(true),
              type = "toggle",
              name = "Enchant weapon " .. itemName .. " automatically",
              width = "full",
              set = "Set",
              get = "GetEnable"
          },
          header = {
              order = self:_AutoIncrementOrder(),
              type = "header",
              name = "Target Slots",
          },
          targetSlotMainHand = {
            order = self:_AutoIncrementOrder(),
            type = "toggle",
            name = "Usable",
            desc = "The " .. itemName .. " must be usable by this character",
            set = "SetTargetSlots",
            get = "GetCriteriaUsable",
            disabled = function()
                return true
            end
          },
        }
    }
end

function WeaponEnchantConfig:GetTargetSlotOptions()
    return {
        [INVENTORY_SLOT_NAME.MAIN_HAND] = "Main Hand",
        [INVENTORY_SLOT_NAME.SECONDARY_HAND] = "Off Hand",
    }
end

function WeaponEnchantConfig:GetDefaults()
    return {
        enable = true,
        targetSlots = {}
    }
end
