---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 20/06/2021 18:38
---
local BagProvider = MasterPrepare.BagProvider
local BAG_PROVIDERS = MasterPrepare.BAG_PROVIDERS

local BagginsBagProvider, super = MasterCore.Class:Create("BagginsBagProvider", BagProvider)

function BagginsBagProvider:IsEnabled()
    return IsAddOnLoaded("Baggins")
end

function BagginsBagProvider:GetButtons()
    local map = {}
    for _, bagFrame in ipairs(Baggins.bagframes) do
        for _, section in ipairs(bagFrame.sections) do
            for _, itemButton in ipairs(section.items) do
                local bag = itemButton:GetParent():GetID()
                local slot = itemButton:GetID()
                local itemLink = GetContainerItemLink(bag, slot)
                local itemID = GetItemID(itemLink)
                if itemID then
                    map[itemID] = itemButton
                end
            end
        end
    end

    return map
end

BAG_PROVIDERS["Baggins"] = BagginsBagProvider:Init()