---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 20/06/2021 18:36
---
local BAG_PROVIDERS = {}
MasterPrepare.BAG_PROVIDERS = BAG_PROVIDERS

local BagProvider, super = MasterCore.Class:Create("BagProvider")
MasterPrepare.BagProvider = BagProvider

function BagProvider:IsEnabled()
    return false
end

function BagProvider:GetButtons()
    return {}
end