---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 24/06/2021 16:56
---
local BagProvider = MasterPrepare.BagProvider
local BAG_PROVIDERS = MasterPrepare.BAG_PROVIDERS

local CombuctorBagProvider, super = MasterCore.Class:Create("CombuctorBagProvider", BagProvider)

function CombuctorBagProvider:IsEnabled()
    return IsAddOnLoaded("Combuctor")
end

function CombuctorBagProvider:GetButtons()
    local buttons = {}
    for bagNumber = 0, NUM_BAG_SLOTS do
        for slotNumber = 1, 36 do
            local itemButton = _G["ContainerFrame" .. bagNumber + 1 .. "Item" .. slotNumber]

            local itemButtonParent = itemButton:GetParent()
            if itemButtonParent then
                local bag = itemButtonParent:GetID()
                local slot = itemButton:GetID()
                local itemLink = GetContainerItemLink(bag, slot)

                local itemID = GetItemID(itemLink)
                if itemID then
                    table.insert(buttons, {
                        itemID = itemID,
                        frame = itemButton
                    })
                end
            end
        end
    end

    return buttons
end

BAG_PROVIDERS["Combuctor"] = CombuctorBagProvider:Init()