---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 14/06/2021 11:22
---
local Config = MasterPrepare.Config
local BagController = MasterPrepare.BagController
local SCRIPT_HANDLER = MasterCore.SCRIPT_HANDLER
local DebuffButtonController = MasterPrepare.DebuffButtonController
local ActionButtonController = MasterPrepare.ActionButtonController
local FW_TYPE = MasterPrepare.FW_TYPE
local AceEvent = LibStub("AceEvent-3.0")
local MESSAGE = MasterPrepare.MESSAGE

MasterPrepareAddon = LibStub("AceAddon-3.0"):NewAddon(MASTER_PREPARE_NAME, "AceConsole-3.0")
function MasterPrepareAddon:OnInitialize()
    Config:Setup()

    local frame = CreateFrame("Frame")
    local bagController = BagController:Init()
    frame:SetScript(SCRIPT_HANDLER.ON_UPDATE, function()
        bagController:OnUpdate()
    end)

    local debuffButtonController = DebuffButtonController:Init()
    RegisterEventsForControllers(
            MasterPrepare.PreparationController:Init(),
            debuffButtonController
    )

    local food = ActionButtonController:Init(FW_TYPE.FOOD)
    local water = ActionButtonController:Init(FW_TYPE.WATER)
    local healing = ActionButtonController:Init(FW_TYPE.HEALING_POTION)
    local mana = ActionButtonController:Init(FW_TYPE.MANA_POTION)
    AceEvent:RegisterMessage(MESSAGE.PREPRATION_CHECKED, function(message, isPrepared, ...)
        food:OnMessage(message, ...)
        water:OnMessage(message, ...)
        healing:OnMessage(message, ...)
        mana:OnMessage(message, ...)
        debuffButtonController:OnMessage(message, isPrepared, ...)
    end)
end
