---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 14/06/2021 11:22
---
local Config = MasterPrepare.Config

MasterPrepareAddon = LibStub("AceAddon-3.0"):NewAddon(MASTER_PREPARE_NAME, "AceConsole-3.0")
function MasterPrepareAddon:OnInitialize()
    local frame = CreateFrame("Frame")

    Config:Setup()
    RegisterEventsForControllers(frame, MasterPrepare.PreparationController:Init())
end