---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 20/06/2021 20:17
---
local BAG_PROVIDERS = MasterPrepare.BAG_PROVIDERS
local AceEvent = LibStub("AceEvent-3.0")
local MESSAGE = MasterPrepare.MESSAGE
local POINT = MasterCore.POINT

local SHOWING_MARKERS_STATUS = {
    READY = 1,
    IN_PROGRESS = 2,
    DONE = 3
}
local BagJunkMarkerController, super = MasterCore.Class:Create("BagJunkMarkerController")
MasterPrepare.BagJunkMarkerController = BagJunkMarkerController

function BagJunkMarkerController:Init()
    self = super.Init(self)
    self.bagProviders = self:_GetBagProviders()
    self.showingMarkersStatus = SHOWING_MARKERS_STATUS.DONE
    self.junkItems = {}
    self.markedButtons = {}
    AceEvent:RegisterMessage(MESSAGE.JUNK_ITEMS_UPDATED, function(_, items)
        self:_HideAllMarkers()
        self.junkItems = items
        self.showingMarkersStatus = SHOWING_MARKERS_STATUS.READY
    end)
    return self
end

function BagJunkMarkerController:OnUpdate()
    if self.showingMarkersStatus == SHOWING_MARKERS_STATUS.READY then
        self:_ShowMarkers()
    end
end
function BagJunkMarkerController:_ShowMarkers()
    self.showingMarkersStatus = SHOWING_MARKERS_STATUS.IN_PROGRESS
    for itemID, _ in pairs(self.junkItems) do
        for _, provider in ipairs(self.bagProviders) do
            local buttons = provider:GetButtons()

            if buttons[itemID] then
                self:_ShowMarker(buttons[itemID])
                table.insert(self.markedButtons, buttons[itemID])
            else
                -- Stop when can't find item button
                -- and keep refresh until all item buttons available
                -- to mark
                self.showingMarkersStatus = SHOWING_MARKERS_STATUS.READY
                return
            end

        end
    end

    self.showingMarkersStatus = SHOWING_MARKERS_STATUS.DONE
end

function BagJunkMarkerController:_ShowMarker(button)
    if not button.junkMarkerIcon then
        local icon = button:CreateTexture(nil, 'OVERLAY')
        icon:SetTexture('Interface/Buttons/UI-GroupLoot-Coin-Up')
        icon:SetPoint(POINT.BOTTOM_RIGHT, 2, -2)
        icon:SetSize(15, 15)

        button.junkMarkerIcon = icon
    end
    button.junkMarkerIcon:Show()
end

function BagJunkMarkerController:_HideAllMarkers()
    for _, button in ipairs(self.markedButtons) do
        if button.junkMarkerIcon then
            button.junkMarkerIcon:Hide()
        end
    end
    self.markedButtons = {}
end

function BagJunkMarkerController:_GetBagProviders()
    local providers = {}
    for _, provider in pairs(BAG_PROVIDERS) do
        if provider:IsEnabled() then
            table.insert(providers, provider)
        end
    end

    return providers
end
