---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 15/06/2021 17:52
---

MasterPrepare.VENDOR_DRINKS = {
    { id = 159, effectValue = 151, minLevel = 1 }, -- Refreshing Spring Water
    { id = 1179, effectValue = 437, minLevel = 5 }, -- Ice Cold Milk
    { id = 17404, effectValue = 437, minLevel = 5 }, -- Blended Bean Brew
    { id = 1205, effectValue = 835, minLevel = 15 }, -- Melon Juice
    { id = 19299, effectValue = 835, minLevel = 15 }, -- Fizzy Faire Drink
    { id = 1708, effectValue = 1345, minLevel = 25 }, -- Sweet Nectar
    { id = 1645, effectValue = 1992, minLevel = 35 }, -- Moonberry Juice
    { id = 19300, effectValue = 1992, minLevel = 35 }, -- Bottled Winterspring Water
    --{ id = 13724, effectValue = 2148, minLevel = 45 }, -- Enriched Manna Biscuit
    { id = 8766, effectValue = 2934, minLevel = 45 }, -- Morning Glory Dew
    { id = 38429, effectValue = 2934, minLevel = 45 }, -- Blackrock Spring Water
    { id = 32455, effectValue = 4200, minLevel = 55 }, -- Star's Lament
    { id = 29454, effectValue = 5100, minLevel = 55 }, -- Silverwine
    { id = 28399, effectValue = 5100, minLevel = 60 }, -- Filtered Draenic Water
    { id = 38430, effectValue = 5100, minLevel = 60 }, -- Blackrock Mineral Water
    { id = 27860, effectValue = 7200, minLevel = 65 }, -- Purified Draenic Water
    { id = 32453, effectValue = 7200, minLevel = 65 }, -- Star's Tears
    { id = 33042, effectValue = 7200, minLevel = 65 }, -- Black Coffee
    { id = 29395, effectValue = 7200, minLevel = 65 }, -- Ethermead
    { id = 32722, effectValue = 4320, minLevel = 65 }, -- Enriched Terocone Juice
    { id = 29401, effectValue = 7200, minLevel = 65 }, -- Sparkling Southshore Cider
    { id = 38431, effectValue = 7200, minLevel = 65 }, -- Blackrock Fortified Water
}