---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 15/06/2021 17:52
---


MasterPrepare.VENDOR_FOODS = {
    { id = 11109, effectValue = 30, minLevel = 1 }, -- Special Chicken Feed
    { id = 4536, effectValue = 61.2, minLevel = 1 }, -- Shiny Red Apple
    { id = 117, effectValue = 61.2, minLevel = 1 }, -- Tough Jerky
    { id = 787, effectValue = 61.2, minLevel = 1 }, -- Slitherskin Mackerel
    { id = 17344, effectValue = 61.2, minLevel = 1 }, -- Candy Cane
    { id = 20857, effectValue = 61.2, minLevel = 1 }, -- Honey Bread
    { id = 4604, effectValue = 61.2, minLevel = 1 }, -- Forest Mushroom Cap
    { id = 19223, effectValue = 61.2, minLevel = 1 }, -- Darkmoon Dog
    { id = 2070, effectValue = 61.2, minLevel = 1 }, -- Darnassian Bleu
    { id = 4540, effectValue = 61.2, minLevel = 1 }, -- Tough Hunk of Bread
    { id = 16166, effectValue = 61.2, minLevel = 1 }, -- Bean Soup
    { id = 4592, effectValue = 243.6, minLevel = 5 }, -- Longjaw Mud Snapper
    { id = 2287, effectValue = 243.6, minLevel = 5 }, -- Haunch of Meat
    { id = 4537, effectValue = 243.6, minLevel = 5 }, -- Tel'Abim Banana
    { id = 4541, effectValue = 243.6, minLevel = 5 }, -- Freshly Baked Bread
    { id = 16167, effectValue = 243.6, minLevel = 5 }, -- Versicolor Treat
    { id = 17406, effectValue = 243.6, minLevel = 5 }, -- Holiday Cheesewheel
    { id = 414, effectValue = 243.6, minLevel = 5 }, -- Dalaran Sharp
    { id = 4605, effectValue = 243.6, minLevel = 5 }, -- Red-speckled Mushroom
    { id = 17119, effectValue = 243.6, minLevel = 5 }, -- Deeprun Rat Kabob
    { id = 18633, effectValue = 243.6, minLevel = 5 }, -- Styleen's Sour Suckerpop
    { id = 19304, effectValue = 243.6, minLevel = 5 }, -- Spiced Beef Jerky
    { id = 4593, effectValue = 552, minLevel = 15 }, -- Bristle Whisker Catfish
    { id = 3770, effectValue = 552, minLevel = 15 }, -- Mutton Chop
    { id = 7228, effectValue = 552, minLevel = 15 }, -- Tigule and Foror's Strawberry Ice Cream
    { id = 4538, effectValue = 552, minLevel = 15 }, -- Snapvine Watermelon
    { id = 16170, effectValue = 552, minLevel = 15 }, -- Steamed Mandu
    { id = 422, effectValue = 552, minLevel = 15 }, -- Dwarven Mild
    { id = 4606, effectValue = 552, minLevel = 15 }, -- Spongy Morel
    { id = 19305, effectValue = 552, minLevel = 15 }, -- Pickled Kodo Foot
    { id = 4542, effectValue = 552, minLevel = 15 }, -- Moist Cornbread
    { id = 4539, effectValue = 874.8, minLevel = 25 }, -- Goldenbark Apple
    { id = 4594, effectValue = 874.8, minLevel = 25 }, -- Rockscale Cod
    { id = 3771, effectValue = 874.8, minLevel = 25 }, -- Wild Hog Shank
    { id = 4544, effectValue = 874.8, minLevel = 25 }, -- Mulgore Spice Bread
    { id = 18632, effectValue = 874.8, minLevel = 25 }, -- Moonbrook Riot Taffy
    { id = 1707, effectValue = 874.8, minLevel = 25 }, -- Stormwind Brie
    { id = 4607, effectValue = 874.8, minLevel = 25 }, -- Delicious Cave Mold
    { id = 17407, effectValue = 874.8, minLevel = 25 }, -- Graccu's Homemade Meat Pie
    { id = 16169, effectValue = 874.8, minLevel = 25 }, -- Wild Ricecake
    { id = 19224, effectValue = 874.8, minLevel = 25 }, -- Red Hot Wings
    { id = 4599, effectValue = 1392, minLevel = 35 }, -- Cured Ham Steak
    { id = 4602, effectValue = 1392, minLevel = 35 }, -- Moon Harvest Pumpkin
    { id = 4608, effectValue = 1392, minLevel = 35 }, -- Raw Black Truffle
    { id = 4601, effectValue = 1392, minLevel = 35 }, -- Soft Banana Bread
    { id = 3927, effectValue = 1392, minLevel = 35 }, -- Fine Aged Cheddar
    { id = 21552, effectValue = 1392, minLevel = 35 }, -- Striped Yellowtail
    { id = 16168, effectValue = 1392, minLevel = 35 }, -- Heaven Peach
    { id = 18635, effectValue = 1392, minLevel = 35 }, -- Bellara's Nutterbar
    { id = 17408, effectValue = 1392, minLevel = 35 }, -- Spicy Beefstick
}