---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 15/06/2021 17:52
---


MasterPrepare.VENDOR_FOODS = {
    { id = 11109, effectValue = 30, minLevel = 1 }, -- Special Chicken Feed
    { id = 4536, effectValue = 61.2, minLevel = 1 }, -- Shiny Red Apple
    { id = 117, effectValue = 61.2, minLevel = 1 }, -- Tough Jerky
    { id = 787, effectValue = 61.2, minLevel = 1 }, -- Slitherskin Mackerel
    { id = 17344, effectValue = 61.2, minLevel = 1 }, -- Candy Cane
    { id = 20857, effectValue = 61.2, minLevel = 1 }, -- Honey Bread
    { id = 4604, effectValue = 61.2, minLevel = 1 }, -- Forest Mushroom Cap
    { id = 19223, effectValue = 61.2, minLevel = 1 }, -- Darkmoon Dog
    { id = 2070, effectValue = 61.2, minLevel = 1 }, -- Darnassian Bleu
    { id = 4540, effectValue = 61.2, minLevel = 1 }, -- Tough Hunk of Bread
    { id = 16166, effectValue = 61.2, minLevel = 1 }, -- Bean Soup
    { id = 4592, effectValue = 243.6, minLevel = 5 }, -- Longjaw Mud Snapper
    { id = 2287, effectValue = 243.6, minLevel = 5 }, -- Haunch of Meat
    { id = 4537, effectValue = 243.6, minLevel = 5 }, -- Tel'Abim Banana
    { id = 4541, effectValue = 243.6, minLevel = 5 }, -- Freshly Baked Bread
    { id = 16167, effectValue = 243.6, minLevel = 5 }, -- Versicolor Treat
    { id = 17406, effectValue = 243.6, minLevel = 5 }, -- Holiday Cheesewheel
    { id = 414, effectValue = 243.6, minLevel = 5 }, -- Dalaran Sharp
    { id = 4605, effectValue = 243.6, minLevel = 5 }, -- Red-speckled Mushroom
    { id = 17119, effectValue = 243.6, minLevel = 5 }, -- Deeprun Rat Kabob
    { id = 18633, effectValue = 243.6, minLevel = 5 }, -- Styleen's Sour Suckerpop
    { id = 19304, effectValue = 243.6, minLevel = 5 }, -- Spiced Beef Jerky
    { id = 4593, effectValue = 552, minLevel = 15 }, -- Bristle Whisker Catfish
    { id = 3770, effectValue = 552, minLevel = 15 }, -- Mutton Chop
    { id = 7228, effectValue = 552, minLevel = 15 }, -- Tigule and Foror's Strawberry Ice Cream
    { id = 4538, effectValue = 552, minLevel = 15 }, -- Snapvine Watermelon
    { id = 16170, effectValue = 552, minLevel = 15 }, -- Steamed Mandu
    { id = 422, effectValue = 552, minLevel = 15 }, -- Dwarven Mild
    { id = 4606, effectValue = 552, minLevel = 15 }, -- Spongy Morel
    { id = 19305, effectValue = 552, minLevel = 15 }, -- Pickled Kodo Foot
    { id = 4542, effectValue = 552, minLevel = 15 }, -- Moist Cornbread
    { id = 4539, effectValue = 874.8, minLevel = 25 }, -- Goldenbark Apple
    { id = 4594, effectValue = 874.8, minLevel = 25 }, -- Rockscale Cod
    { id = 3771, effectValue = 874.8, minLevel = 25 }, -- Wild Hog Shank
    { id = 4544, effectValue = 874.8, minLevel = 25 }, -- Mulgore Spice Bread
    { id = 18632, effectValue = 874.8, minLevel = 25 }, -- Moonbrook Riot Taffy
    { id = 1707, effectValue = 874.8, minLevel = 25 }, -- Stormwind Brie
    { id = 4607, effectValue = 874.8, minLevel = 25 }, -- Delicious Cave Mold
    { id = 17407, effectValue = 874.8, minLevel = 25 }, -- Graccu's Homemade Meat Pie
    { id = 16169, effectValue = 874.8, minLevel = 25 }, -- Wild Ricecake
    { id = 19224, effectValue = 874.8, minLevel = 25 }, -- Red Hot Wings
    { id = 4599, effectValue = 1392, minLevel = 35 }, -- Cured Ham Steak
    { id = 4602, effectValue = 1392, minLevel = 35 }, -- Moon Harvest Pumpkin
    { id = 4608, effectValue = 1392, minLevel = 35 }, -- Raw Black Truffle
    { id = 4601, effectValue = 1392, minLevel = 35 }, -- Soft Banana Bread
    { id = 3927, effectValue = 1392, minLevel = 35 }, -- Fine Aged Cheddar
    { id = 21552, effectValue = 1392, minLevel = 35 }, -- Striped Yellowtail
    { id = 16168, effectValue = 1392, minLevel = 35 }, -- Heaven Peach
    { id = 18635, effectValue = 1392, minLevel = 35 }, -- Bellara's Nutterbar
    { id = 17408, effectValue = 1392, minLevel = 35 }, -- Spicy Beefstick
    { id = 19306, effectValue = 1392, minLevel = 35 }, -- Crunchy Frog
    { id = 21030, effectValue = 1392, minLevel = 35 }, -- Darnassus Kimchi Pie
    { id = 8932, effectValue = 2148, minLevel = 45 }, -- Alterac Swiss
    { id = 13724, effectValue = 2148, minLevel = 45 }, -- Enriched Manna Biscuit
    { id = 8952, effectValue = 2148, minLevel = 45 }, -- Roasted Quail
    { id = 19225, effectValue = 2148, minLevel = 45 }, -- Deep Fried Candybar
    { id = 8953, effectValue = 2148, minLevel = 45 }, -- Deep Fried Plantains
    { id = 11444, effectValue = 2148, minLevel = 45 }, -- Grim Guzzler Boar
    { id = 8957, effectValue = 2148, minLevel = 45 }, -- Spinefin Halibut
    { id = 22324, effectValue = 2148, minLevel = 45 }, -- Winter Kimchi
    { id = 8950, effectValue = 2148, minLevel = 45 }, -- Homemade Cherry Pie
    { id = 8948, effectValue = 2148, minLevel = 45 }, -- Dried King Bolete
    { id = 21031, effectValue = 2148, minLevel = 45 }, -- Cabbage Kimchi
    { id = 23160, effectValue = 2148, minLevel = 45 }, -- Friendship Bread
    { id = 21033, effectValue = 2148, minLevel = 45 }, -- Radish Kimchi
    { id = 27858, effectValue = 4320, minLevel = 55 }, -- Sunspring Carp
    { id = 27854, effectValue = 4320, minLevel = 55 }, -- Smoked Talbuk Venison
    { id = 27859, effectValue = 4320, minLevel = 55 }, -- Zangar Caps
    { id = 27856, effectValue = 4320, minLevel = 55 }, -- Skethyl Berries
    { id = 27855, effectValue = 4320, minLevel = 55 }, -- Mag'har Grainbread
    { id = 27857, effectValue = 4320, minLevel = 55 }, -- Garadar Sharp
    { id = 24539, effectValue = 4320, minLevel = 55 }, -- Marsh Lichen
    { id = 24008, effectValue = 4320, minLevel = 55 }, -- Dried Mushroom Rations
    { id = 24009, effectValue = 4320, minLevel = 55 }, -- Dried Fruit Rations
    { id = 29393, effectValue = 4320, minLevel = 55 }, -- Diamond Berries
    { id = 29412, effectValue = 4320, minLevel = 55 }, -- Jessen's Special Slop
    { id = 32721, effectValue = 6000, minLevel = 55 }, -- Skyguard Rations
    { id = 28486, effectValue = 4320, minLevel = 55 }, -- Moser's Magnificent Muffin
    { id = 38427, effectValue = 4320, minLevel = 55 }, -- Pickled Egg
    { id = 29451, effectValue = 7500, minLevel = 65 }, -- Clefthoof Ribs
    { id = 29453, effectValue = 7500, minLevel = 65 }, -- Sporeggar Mushroom
    { id = 29449, effectValue = 7500, minLevel = 65 }, -- Bladespire Bagel
    { id = 29450, effectValue = 7500, minLevel = 65 }, -- Telaari Grapes
    { id = 29448, effectValue = 7500, minLevel = 65 }, -- Mag'har Mild Cheese
    { id = 29452, effectValue = 7500, minLevel = 65 }, -- Zangar Trout
    { id = 29394, effectValue = 7500, minLevel = 65 }, -- Lyribread
    { id = 32722, effectValue = 4320, minLevel = 65 }, -- Enriched Terocone Juice
    { id = 38428, effectValue = 7500, minLevel = 65 }, -- Rock-Salted Pretzel
    { id = 30355, effectValue = 7500, minLevel = 65 }, -- Grilled Shadowmoon Tuber
}