---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 08/08/2021 09:53
---
MasterPrepare.HEALING_POTIONS = {
    { id = 118, effectValue = 70, minLevel = 1 }, -- Minor Healing Potion
    { id = 858, effectValue = 140, minLevel = 3 }, -- Lesser Healing Potion
    { id = 4596, effectValue = 140, minLevel = 5 }, -- Discolored Healing Potion
    { id = 929, effectValue = 280, minLevel = 12 }, -- Healing Potion
    { id = 1710, effectValue = 455, minLevel = 21 }, -- Greater Healing Potion
    { id = 3928, effectValue = 700, minLevel = 35 }, -- Superior Healing Potion
    { id = 18839, effectValue = 700, minLevel = 35 }, -- Combat Healing Potion
    { id = 13446, effectValue = 1050, minLevel = 45 }, -- Major Healing Potion
    { id = 28100, effectValue = 1050, minLevel = 55 }, -- Volatile Healing Potion
    { id = 33934, effectValue = 1500, minLevel = 55 }, -- Crystal Healing Potion
    { id = 22829, effectValue = 1500, minLevel = 55 }, -- Super Healing Potion
    { id = 32947, effectValue = 1500, minLevel = 55 }, -- Auchenai Healing Potion
    { id = 33092, effectValue = 1500, minLevel = 55 }, -- Healing Potion Injector
    { id = 23822, effectValue = 1500, minLevel = 55 }, -- Healing Potion Injector
    { id = 31853, effectValue = 1050, minLevel = 61 }, -- Major Combat Healing Potion
    { id = 31839, effectValue = 1050, minLevel = 61 }, -- Major Combat Healing Potion
    { id = 31852, effectValue = 1050, minLevel = 61 }, -- Major Combat Healing Potion
    { id = 31838, effectValue = 1050, minLevel = 61 }, -- Major Combat Healing Potion
}

MasterPrepare.MANA_POTIONS = {
    { id = 2455, effectValue = 140, minLevel = 5 }, -- Minor Mana Potion
    { id = 3385, effectValue = 280, minLevel = 14 }, -- Lesser Mana Potion
    { id = 3827, effectValue = 455, minLevel = 22 }, -- Mana Potion
    { id = 6149, effectValue = 700, minLevel = 31 }, -- Greater Mana Potion
    { id = 13443, effectValue = 900, minLevel = 41 }, -- Superior Mana Potion
    { id = 13444, effectValue = 1350, minLevel = 49 }, -- Major Mana Potion
    { id = 28101, effectValue = 1350, minLevel = 55 }, -- Unstable Mana Potion
    { id = 22832, effectValue = 1800, minLevel = 55 }, -- Super Mana Potion
    { id = 33093, effectValue = 1800, minLevel = 55 }, -- Mana Potion Injector
    { id = 31677, effectValue = 3200, minLevel = 60 }, -- Fel Mana Potion
}