---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 19/06/2021 08:44
---
local Config, super = MasterCore.Class:Create("Config")
MasterCore.Config = Config

function Config:Init(db, order)
    self = super.Init(self)
    self.db = db
    self.order = order
    return self
end

function Config:_AutoIncrementOrder(reset)
    if reset then
        self._autoIncrementOrder = 0
    end

    self._autoIncrementOrder = self._autoIncrementOrder + 1
    return self._autoIncrementOrder
end

function Config:_GetKey(info)
    local key = info
    if type(info) == "table" then
        key = info[#info]
    end

    return key
end
function Config:Set(info, value)
    local key = self:_GetKey(info)
    self.db[key] = value
end

function Config:Get(info)
    local key = self:_GetKey(info)
    return self.db[key]
end