---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 08/06/2021 18:08
---
MasterCore.FRAME_TYPE = {
    FRAME = "Frame",
    CHECK_BUTTON = "CheckButton",
    BUTTON = "Button"
}

MasterCore.FRAME_TEMPLATE = {
    DEBUFF_BUTTON = "DebuffButtonTemplate"
}

MasterCore.MOUSE_BUTTON = {
    LEFT_BUTTON = "LeftButton",
    RIGHT_BUTTON = "RightButton"
}

MasterCore.CLICK_TYPE = {
    LEFT_BUTTON_UP = "LeftButtonUp",
    RIGHT_BUTTON_UP = "RightButtonUp",
    MIDDLE_BUTTON_UP = "MiddleButtonUp",
    BUTTON4_UP = "Button4Up",
    BUTTON5_UP = "Button5Up",
    LEFT_BUTTON_DOWN = "LeftButtonDown",
    RIGHT_BUTTON_DOWN = "RightButtonDown",
    MIDDLE_BUTTON_DOWN = "MiddleButtonDown",
    BUTTON4_DOWN = "Button4Down",
    BUTTON5_DOWN = "Button5Down",
    ANY_UP = "AnyUp",
    ANY_DOWN = "AnyDown",
}

MasterCore.UNIT = {
    PLAYER = "player",
    TARGET = "target"
}

MasterCore.UNIT_CLASS = {
    SHAMAN = "Shaman"
}

MasterCore.SCRIPT_HANDLER = {
    ON_DRAG_START = "OnDragStart",
    ON_DRAG_STOP = "OnDragStop",
    ON_EVENT = "OnEvent",
    ON_UPDATE = "OnUpdate",
    ON_ENTER = "OnEnter",
    ON_LEAVE = "OnLeave"
}

MasterCore.POINT = {
    TOP = "TOP",
    RIGHT = "RIGHT",
    BOTTOM = "BOTTOM",
    LEFT = "LEFT",
    TOP_RIGHT = "TOPRIGHT",
    TOP_LEFT = "TOPLEFT",
    BOTTOM_LEFT = "BOTTOMLEFT",
    BOTTOM_RIGHT = "BOTTOMRIGHT",
    CENTER = "CENTER"
}

MasterCore.EVENT = {
    ADDON_LOADED = "ADDON_LOADED",
    PLAYER_TARGET_CHANGED = "PLAYER_TARGET_CHANGED",
    NAME_PLATE_UNIT_ADDED = "NAME_PLATE_UNIT_ADDED",
    PLAYER_ENTER_COMBAT = "PLAYER_ENTER_COMBAT",
    PLAYER_LEAVE_COMBAT = "PLAYER_LEAVE_COMBAT",
    COMBAT_LOG_EVENT_UNFILTERED = "COMBAT_LOG_EVENT_UNFILTERED",
    MERCHANT_SHOW = "MERCHANT_SHOW",
    BAG_UPDATE = "BAG_UPDATE",
    BAG_OPEN = "BAG_OPEN",
    TAXIMAP_OPENED = "TAXIMAP_OPENED",
    CONFIRM_SUMMON = "CONFIRM_SUMMON",
    UNIT_AURA = "UNIT_AURA",
    PLAYER_ENTERING_WORLD = "PLAYER_ENTERING_WORLD"
}

MasterCore.COMBAT_LOG_EVENT = {
    SPELL_CAST_START = "SPELL_CAST_START",
    SPELL_CAST_FAILED = "SPELL_CAST_FAILED",
    SPELL_CAST_SUCCESS = "SPELL_CAST_SUCCESS",
    SPELL_INTERRUPT = "SPELL_INTERRUPT",
    UNIT_DIED = "UNIT_DIED"
}

MasterCore.INVENTORY_SLOT_NAME = {
    HEAD = "HeadSlot",
    NECK = "NeckSlot",
    SHOULDER = "ShoulderSlot",
    BACK = "BackSlot",
    CHEST = "ChestSlot",
    SHIRT = "ShirtSlot",
    TABARD = "TabardSlot",
    WRIST = "WristSlot",
    HANDS = "HandsSlot",
    WAIST = "WaistSlot",
    LEGS = "LegsSlot",
    FEET = "FeetSlot",
    FINGER_0 = "Finger0Slot",
    FINGER_1 = "Finger1Slot",
    TRINKET_0 = "Trinket0Slot",
    TRINKET_1 = "Trinket1Slot",
    MAIN_HAND = "MainHandSlot",
    SECONDARY_HAND = "SecondaryHandSlot",
    BAG_0 = "Bag0Slot",
    BAG_1 = "Bag1Slot",
    BAG_2 = "Bag2Slot",
    BAG_3 = "Bag3Slot"
}

MasterCore.ITEM_QUALITY = {
    POOR = 0,
    COMMON = 1,
    UNCOMMON = 2,
    RARE = 3,
    EPIC = 4,
    LEGENDARY = 5,
    ARTIFACT = 6,
}

MasterCore.ITEM_TYPE = {
    ARMOR = "Armor",
    WEAPON = "Weapon"
}