---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markg.
--- DateTime: 27/06/2021 10:48
---
--- Returns merged table from two input tables
--- @param t1 table @ The first table needs to merge
--- @param t2 table @ The second table needs to merge
--- @return table
function table.merge(t1, t2)
    for k,v in pairs(t2) do
        if type(v) == "table" then
            if type(t1[k] or false) == "table" then
                tableMerge(t1[k] or {}, t2[k] or {})
            else
                t1[k] = v
            end
        else
            t1[k] = v
        end
    end
    return t1
end

--- Checks whether table is emptied or not
--- @param table table @ The table needs to check
--- @return boolean
function table.isEmpty(table)
    return next(table) == nil
end

